#spring:
#  application:
#    name: alibaba-nacos-config-client
#server:
#  port: 9005
# spring.cloud.nacos.config.server-addr=localhost:8848

#spring.cloud.nacos:
#  config.server-addr: localhost:8848
